name: PR Build

on: [pull_request]

jobs:
  build:
    name: Build, Test, Pack
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - name: .NET Build
      run: dotnet build -c Release /p:CI=true
    - name: .NET Test
      run: dotnet test -c Release --no-build /p:CI=true
    - name: .NET Lib Pack
      run: dotnet pack --no-build -c Release /p:Packing=true /p:CI=true